"""payShield 10K simulator — driven over a real socket with framed commands.

Validates the wire format (length prefix + echoed header + response/error code)
and the hybrid crypto: keys minted by A0 check out under BU, a CVV generated by
CW verifies under CY (and a wrong one is rejected), a PIN translated TPK->ZPK by
CA decodes back to the same PIN, EC verifies a PVV, and M6/M8 round-trip a MAC.
"""

import asyncio

from worker.adapters.hsm.payshield import PayShieldSimulator
from worker.engine import crypto_tools as ct

HEADER = "HDR1"


async def _start(config=None):
    sim = PayShieldSimulator(config or {"host": "127.0.0.1", "port": 0})
    port = await sim.start()
    return sim, port


async def _send(port: int, command: str, data: str = "") -> dict:
    """Send one framed payShield command, return the decoded response dict."""
    reader, writer = await asyncio.open_connection("127.0.0.1", port)
    body = f"{HEADER}{command}{data}".encode("ascii")
    writer.write(len(body).to_bytes(2, "big") + body)
    await writer.drain()
    prefix = await reader.readexactly(2)
    resp = await reader.readexactly(int.from_bytes(prefix, "big"))
    writer.close()
    text = resp.decode("ascii")
    return {
        "header": text[:4],
        "response": text[4:6],
        "error": text[6:8],
        "data": text[8:],
    }


async def test_nc_diagnostics():
    sim, port = await _start()
    try:
        r = await _send(port, "NC")
        assert r["header"] == HEADER
        assert r["response"] == "ND"
        assert r["error"] == "00"
        # 16-digit LMK check value + 9-char firmware "xxxx-xxxx".
        assert len(r["data"]) == 25
        assert r["data"][20] == "-"  # firmware "xxxx-xxxx" dash
    finally:
        await sim.stop()


async def test_a0_generate_then_bu_checks_out():
    sim, port = await _start()
    try:
        gen = await _send(port, "A0", "1002U")  # mode 1, TPK (002), double-length
        assert gen["response"] == "A1" and gen["error"] == "00"
        token, kcv = gen["data"][:33], gen["data"][33:39]
        assert token[0] == "U" and len(kcv) == 6
        # BU on the same token must reproduce the KCV A0 returned.
        chk = await _send(port, "BU", "00" + "1" + token)
        assert chk["response"] == "BV" and chk["error"] == "00"
        assert chk["data"][:6] == kcv
    finally:
        await sim.stop()


async def test_cw_then_cy_verifies_and_rejects():
    sim, port = await _start()
    try:
        cvk = (await _send(port, "A0", "1402U"))["data"][:33]  # CVK (402)
        pan, expiry, sc = "4000000000000002", "2512", "000"
        gen = await _send(port, "CW", f"{cvk}{pan};{expiry}{sc}")
        assert gen["response"] == "CX" and gen["error"] == "00"
        cvv = gen["data"]
        assert len(cvv) == 3 and cvv.isdigit()
        ok = await _send(port, "CY", f"{cvk}{cvv}{pan};{expiry}{sc}")
        assert ok["response"] == "CZ" and ok["error"] == "00"
        bad = await _send(port, "CY", f"{cvk}999{pan};{expiry}{sc}")
        assert bad["error"] == "01"
    finally:
        await sim.stop()


async def test_ca_pin_translate_round_trips():
    sim, port = await _start()
    try:
        tpk = (await _send(port, "A0", "1002U"))["data"][:33]
        zpk = (await _send(port, "A0", "1001U"))["data"][:33]
        pan, pin = "400000000000000002", "1234"
        # build an ISO-0 PIN block under the clear TPK to feed the simulator
        clear_tpk = sim.ctx.lmk.unwrap(tpk)
        src_block = ct.pin_block_encode(pin, pan, clear_tpk)["pin_block"]
        pan12 = "".join(c for c in pan if c.isdigit())[-13:-1]
        r = await _send(port, "CA", f"{tpk}{zpk}12{src_block}0101{pan12}")
        assert r["response"] == "CB" and r["error"] == "00"
        out_len, out_block = r["data"][:2], r["data"][2:18]
        assert out_len == "04"
        clear_zpk = sim.ctx.lmk.unwrap(zpk)
        assert ct.pin_block_decode(out_block, pan, clear_zpk)["pin"] == pin
    finally:
        await sim.stop()


async def test_ec_verifies_pvv():
    sim, port = await _start()
    try:
        zpk = (await _send(port, "A0", "1001U"))["data"][:33]
        pvk = (await _send(port, "A0", "1002U"))["data"][:33]
        pan, pin, pvki = "400000000000000002", "1234", "1"
        clear_zpk, clear_pvk = sim.ctx.lmk.unwrap(zpk), sim.ctx.lmk.unwrap(pvk)
        block = ct.pin_block_encode(pin, pan, clear_zpk)["pin_block"]
        pvv = ct.pvv(pan, pin, pvki, clear_pvk)["pvv"]
        pan12 = "".join(c for c in pan if c.isdigit())[-13:-1]
        r = await _send(port, "EC", f"{zpk}{pvk}{block}01{pan12}{pvki}{pvv}")
        assert r["response"] == "ED" and r["error"] == "00"
    finally:
        await sim.stop()


async def test_ca_translates_pin_block_format_iso0_to_iso3():
    """CA reformats between ISO 9564-1 formats: an ISO-0 block under the TPK
    comes back as an ISO-3 block under the ZPK carrying the same PIN."""
    sim, port = await _start()
    try:
        tpk = (await _send(port, "A0", "1002U"))["data"][:33]
        zpk = (await _send(port, "A0", "1001U"))["data"][:33]
        pan, pin = "400000000000000002", "1234"
        clear_tpk = sim.ctx.lmk.unwrap(tpk)
        # source block is ISO-0 (format code 01)
        src_block = ct.pin_block_encode(pin, pan, clear_tpk, "0")["pin_block"]
        pan12 = "".join(c for c in pan if c.isdigit())[-13:-1]
        # src fmt 01 (ISO-0) -> dst fmt 47 (ISO-3)
        r = await _send(port, "CA", f"{tpk}{zpk}12{src_block}0147{pan12}")
        assert r["response"] == "CB" and r["error"] == "00"
        out_block = r["data"][2:18]
        clear_zpk = sim.ctx.lmk.unwrap(zpk)
        # decode the result as ISO-3 -> same PIN; decoding as ISO-0 would differ
        assert ct.pin_block_decode(out_block, pan, clear_zpk, "3")["pin"] == pin
    finally:
        await sim.stop()


async def test_ca_translates_pin_block_format_iso0_to_iso1():
    """ISO-1 carries no PAN, so the destination block decodes without one."""
    sim, port = await _start()
    try:
        tpk = (await _send(port, "A0", "1002U"))["data"][:33]
        zpk = (await _send(port, "A0", "1001U"))["data"][:33]
        pan, pin = "400000000000000002", "580211"
        clear_tpk = sim.ctx.lmk.unwrap(tpk)
        src_block = ct.pin_block_encode(pin, pan, clear_tpk, "0")["pin_block"]
        pan12 = "".join(c for c in pan if c.isdigit())[-13:-1]
        # src fmt 01 (ISO-0) -> dst fmt 05 (ISO-1)
        r = await _send(port, "CA", f"{tpk}{zpk}12{src_block}0105{pan12}")
        assert r["response"] == "CB" and r["error"] == "00"
        assert r["data"][:2] == "06"  # 6-digit PIN length
        out_block = r["data"][2:18]
        clear_zpk = sim.ctx.lmk.unwrap(zpk)
        assert ct.pin_block_decode(out_block, "", clear_zpk, "1")["pin"] == pin
    finally:
        await sim.stop()


async def test_a0_mints_aes_key():
    """A0 with an AES scheme tag (R = AES-128) mints a 16-byte AES key whose
    token round-trips through the LMK."""
    sim, port = await _start()
    try:
        gen = await _send(port, "A0", "1001R")  # AES-128 ZPK
        assert gen["response"] == "A1" and gen["error"] == "00"
        token = gen["data"][:33]
        assert token[0] == "R"
        assert len(sim.ctx.lmk.unwrap(token)) == 32  # 16 bytes = 32 hex
    finally:
        await sim.stop()


async def test_ca_translates_iso0_to_iso4_aes():
    """Translate a DES ISO-0 PIN block into an AES ISO-4 block (format 48)."""
    sim, port = await _start()
    try:
        tpk = (await _send(port, "A0", "1002U"))["data"][:33]  # DES TPK
        zpk = (await _send(port, "A0", "1001R"))["data"][:33]  # AES-128 ZPK
        pan, pin = "400000000000000002", "1234"
        pan12 = "".join(c for c in pan if c.isdigit())[-13:-1]
        src = ct.pin_block_encode(pin, pan12, sim.ctx.lmk.unwrap(tpk), "0")["pin_block"]
        r = await _send(port, "CA", f"{tpk}{zpk}12{src}0148{pan12}")
        assert r["response"] == "CB" and r["error"] == "00"
        block4 = r["data"][2:34]  # ISO-4 block is 16 bytes = 32 hex
        assert len(block4) == 32
        assert ct.pin_block_decode(block4, pan12, sim.ctx.lmk.unwrap(zpk), "4")["pin"] == pin
    finally:
        await sim.stop()


async def test_ca_translates_iso4_back_to_iso0():
    """An AES ISO-4 block (32-hex) translates back to a DES ISO-0 block — the
    PIN-block field width follows the source format, both directions."""
    sim, port = await _start()
    try:
        aes_zpk = (await _send(port, "A0", "1001R"))["data"][:33]
        des_zpk = (await _send(port, "A0", "1001U"))["data"][:33]
        pan, pin = "400000000000000002", "1234"
        pan12 = "".join(c for c in pan if c.isdigit())[-13:-1]
        block4 = ct.pin_block_encode(pin, pan12, sim.ctx.lmk.unwrap(aes_zpk), "4")["pin_block"]
        # src fmt 48 (ISO-4, AES) -> dst fmt 01 (ISO-0, DES)
        r = await _send(port, "CA", f"{aes_zpk}{des_zpk}12{block4}4801{pan12}")
        assert r["response"] == "CB" and r["error"] == "00"
        out0 = r["data"][2:18]
        assert ct.pin_block_decode(out0, pan12, sim.ctx.lmk.unwrap(des_zpk), "0")["pin"] == pin
    finally:
        await sim.stop()


async def test_de_generate_then_ba_verifies_ibm_offset():
    sim, port = await _start()
    try:
        tpk = (await _send(port, "A0", "1002U"))["data"][:33]
        pvk = (await _send(port, "A0", "1002U"))["data"][:33]
        pan, pin = "400000000000000002", "1234"
        dec, val = "0123456789012345", "1122334455667788"
        clear_tpk = sim.ctx.lmk.unwrap(tpk)
        block = ct.pin_block_encode(pin, pan, clear_tpk)["pin_block"]
        pan12 = "".join(c for c in pan if c.isdigit())[-13:-1]
        gen = await _send(port, "DE", f"{tpk}{pvk}{block}01{pan12}{dec}{val}")
        assert gen["response"] == "DF" and gen["error"] == "00"
        offset = gen["data"]
        assert offset and offset.isdigit()
        # BA with the correct offset verifies; a mangled offset is rejected.
        ok = await _send(port, "BA", f"{tpk}{pvk}{block}01{pan12}{dec}{val}{offset}")
        assert ok["response"] == "BB" and ok["error"] == "00"
        bad_off = str((int(offset[0]) + 1) % 10) + offset[1:]
        bad = await _send(port, "BA", f"{tpk}{pvk}{block}01{pan12}{dec}{val}{bad_off}")
        assert bad["error"] == "01"
    finally:
        await sim.stop()


async def test_be_verifies_interchange_ibm_offset():
    sim, port = await _start()
    try:
        zpk = (await _send(port, "A0", "1001U"))["data"][:33]
        pvk = (await _send(port, "A0", "1002U"))["data"][:33]
        pan, pin = "400000000000000002", "1234"
        dec, val = "0123456789012345", "A1B2C3D4E5F60718"
        clear_zpk = sim.ctx.lmk.unwrap(zpk)
        block = ct.pin_block_encode(pin, pan, clear_zpk)["pin_block"]
        pan12 = "".join(c for c in pan if c.isdigit())[-13:-1]
        clear_pvk = sim.ctx.lmk.unwrap(pvk)
        offset = ct.ibm3624_offset(val, clear_pvk, pin, dec)["offset"]
        ok = await _send(port, "BE", f"{zpk}{pvk}{block}01{pan12}{dec}{val}{offset}")
        assert ok["response"] == "BF" and ok["error"] == "00"
    finally:
        await sim.stop()


async def test_ja_generates_pvv_that_ec_verifies():
    sim, port = await _start()
    try:
        zpk = (await _send(port, "A0", "1001U"))["data"][:33]
        pvk = (await _send(port, "A0", "1002U"))["data"][:33]
        pan, pin, pvki = "400000000000000002", "1234", "1"
        clear_zpk = sim.ctx.lmk.unwrap(zpk)
        block = ct.pin_block_encode(pin, pan, clear_zpk)["pin_block"]
        pan12 = "".join(c for c in pan if c.isdigit())[-13:-1]
        gen = await _send(port, "JA", f"{zpk}{pvk}{block}01{pan12}{pvki}")
        assert gen["response"] == "JB" and gen["error"] == "00"
        pvv = gen["data"]
        assert len(pvv) == 4 and pvv.isdigit()
        # the PVV JA generated must verify under EC (the interchange verifier).
        ver = await _send(port, "EC", f"{zpk}{pvk}{block}01{pan12}{pvki}{pvv}")
        assert ver["response"] == "ED" and ver["error"] == "00"
    finally:
        await sim.stop()


async def test_m6_then_m8_verifies_mac():
    sim, port = await _start()
    try:
        mac_key = (await _send(port, "A0", "1008U"))["data"][:33]
        msg = "48656C6C6F31323334"  # "Hello1234" as hex
        gen = await _send(port, "M6", f"{mac_key}{msg}")
        assert gen["response"] == "M7" and gen["error"] == "00"
        mac = gen["data"]
        ok = await _send(port, "M8", f"{mac_key}{msg}{mac}")
        assert ok["error"] == "00"
        bad = await _send(port, "M8", f"{mac_key}{msg}{'0' * 16}")
        assert bad["error"] == "01"
    finally:
        await sim.stop()


async def test_unknown_command_errors():
    sim, port = await _start()
    try:
        r = await _send(port, "ZZ", "")
        assert r["error"] == "30"
    finally:
        await sim.stop()


async def test_scripted_override():
    sim, port = await _start(
        {
            "host": "127.0.0.1",
            "port": 0,
            "commands": {"NC": {"error": "68", "data": "DISABLED"}},
        }
    )
    try:
        r = await _send(port, "NC")
        assert r["error"] == "68" and r["data"] == "DISABLED"
    finally:
        await sim.stop()


async def test_cc_pin_translate_zpk_to_zpk():
    sim, port = await _start()
    try:
        src = (await _send(port, "A0", "1001U"))["data"][:33]
        dst = (await _send(port, "A0", "1001U"))["data"][:33]
        pan, pin = "400000000000000002", "1234"
        clear_src = sim.ctx.lmk.unwrap(src)
        src_block = ct.pin_block_encode(pin, pan, clear_src)["pin_block"]
        pan12 = "".join(c for c in pan if c.isdigit())[-13:-1]
        r = await _send(port, "CC", f"{src}{dst}12{src_block}0101{pan12}")
        assert r["response"] == "CD" and r["error"] == "00"
        out_block = r["data"][2:18]
        clear_dst = sim.ctx.lmk.unwrap(dst)
        assert ct.pin_block_decode(out_block, pan, clear_dst)["pin"] == pin
    finally:
        await sim.stop()


async def test_a6_import_k8_export_round_trip():
    sim, port = await _start()
    try:
        cvk = (await _send(port, "A0", "1402U"))["data"]
        cvk_token, kcv = cvk[:33], cvk[33:39]
        zmk = (await _send(port, "A0", "1000U"))["data"][:33]
        # export the CVK under the ZMK, then import it back — KCV must survive.
        exp = await _send(port, "K8", f"402{cvk_token}{zmk}X")
        assert exp["response"] == "K9" and exp["error"] == "00"
        under_kek = exp["data"][:-6]
        imp = await _send(port, "A6", f"402{zmk}{under_kek}U")
        assert imp["response"] == "A7" and imp["error"] == "00"
        assert imp["data"][33:39] == kcv
    finally:
        await sim.stop()


async def test_g0_dukpt_pin_translate():
    sim, port = await _start()
    try:
        bdk = (await _send(port, "A0", "1302U"))["data"][:33]
        zpk = (await _send(port, "A0", "1001U"))["data"][:33]
        pan, pin, ksn = "400000000000000002", "1234", "FFFF9876543210E00001"
        clear_bdk = sim.ctx.lmk.unwrap(bdk)
        block = ct.dukpt_pin_block(pin, pan, bdk_hex=clear_bdk, ksn_hex=ksn)["pin_block"]
        pan12 = "".join(c for c in pan if c.isdigit())[-13:-1]
        r = await _send(port, "G0", f"{bdk}{zpk}{ksn}{block}0101{pan12}")
        assert r["response"] == "G1" and r["error"] == "00"
        clear_zpk = sim.ctx.lmk.unwrap(zpk)
        assert ct.pin_block_decode(r["data"][2:18], pan, clear_zpk)["pin"] == pin
    finally:
        await sim.stop()


async def test_kq_arqc_verify_and_arpc():
    sim, port = await _start()
    try:
        mkac = (await _send(port, "A0", "1109U"))["data"][:33]
        clear_mkac = sim.ctx.lmk.unwrap(mkac, 1)  # MK-AC variant
        pan, psn, atc, txn = "4000000000000002", "00", "0001", "0000001000"
        udk = ct.emv_icc_mk(clear_mkac, pan, psn)["udk"]
        sk = ct.emv_session_key(udk, atc)["session_key"]
        arqc = ct.arqc(sk, txn)["arqc"]
        txnlen = f"{len(txn) // 2:02X}"
        ok = await _send(port, "KQ", f"10{mkac}{pan}{psn}{atc}{txnlen}{txn};{arqc}3030")
        assert ok["response"] == "KR" and ok["error"] == "00"
        assert len(ok["data"]) == 16  # ARPC returned
        bad = await _send(port, "KQ", f"10{mkac}{pan}{psn}{atc}{txnlen}{txn};{'0' * 16}3030")
        assert bad["error"] == "01"
    finally:
        await sim.stop()


async def test_no_hsm_status_reports_pci_hsm():
    sim, port = await _start({"host": "127.0.0.1", "port": 0, "pci_hsm": True})
    try:
        r = await _send(port, "NO", "01")
        assert r["response"] == "NP" and r["error"] == "00"
        assert r["data"][0] == "1"  # PCI-HSM compliant
    finally:
        await sim.stop()


async def test_disabled_command_returns_68():
    sim, port = await _start(
        {
            "host": "127.0.0.1",
            "port": 0,
            "disabled_commands": ["CW"],
        }
    )
    try:
        r = await _send(port, "CW", "")
        assert r["response"] == "CX" and r["error"] == "68"
    finally:
        await sim.stop()


async def test_variant_lmk_enforces_key_separation():
    """With variant_lmk on, a CVK (variant 4) doesn't check out as a ZPK
    (variant 0): BU with the wrong key type yields a different KCV."""
    sim, port = await _start({"host": "127.0.0.1", "port": 0, "variant_lmk": True})
    try:
        gen = await _send(port, "A0", "1402U")  # CVK, variant 4
        token, kcv = gen["data"][:33], gen["data"][33:39]
        # BU as CVK (type 42 -> 402, variant 4) reproduces the KCV
        right = await _send(port, "BU", f"42 1{token}".replace(" ", ""))
        assert right["data"][:6] == kcv
        # BU as ZPK (type 01 -> 001, variant 0) gets a different clear key -> KCV
        wrong = await _send(port, "BU", f"011{token}")
        assert wrong["data"][:6] != kcv
    finally:
        await sim.stop()
